In [34]:
import pandas as pd

In [35]:
ionosphere = pd.read_csv("results/ionosphere_results.csv", index_col="Unnamed: 0")
ionosphere['dataset'] = 'ionosphere'
ionosphere['dim_reduction'] = 33 - ionosphere['encoding_dim']
ionosphere['accuracy_reduction'] = ionosphere['neural_net_acc'] - ionosphere['auto_classifier_acc']
ionosphere.head()

,auto_classifier_acc,encoding_dim,neural_net_acc,dataset,dim_reduction,accuracy_reduction
0,0.942857,33,0.857143,ionosphere,0,-0.085714
1,0.914286,32,0.857143,ionosphere,1,-0.057143
2,0.857143,31,0.857143,ionosphere,2,0.000000
3,0.857143,30,0.857143,ionosphere,3,0.000000
4,0.942857,29,0.857143,ionosphere,4,-0.085714

In [36]:
robo = pd.read_csv("results/robo_results.csv", index_col="Unnamed: 0")
robo['dataset'] = 'robo'
robo['dim_reduction'] = 24 - robo['encoding_dim']
robo['accuracy_reduction'] = robo['neural_net_acc'] - robo['auto_classifier_acc']
robo.head()

,auto_classifier_acc,encoding_dim,neural_net_acc,dataset,dim_reduction,accuracy_reduction
0,0.939560,24,0.945055,robo,0,0.005495
1,0.939560,23,0.945055,robo,1,0.005495
2,0.935897,22,0.945055,robo,2,0.009158
3,0.959707,21,0.945055,robo,3,-0.014652
4,0.928571,20,0.945055,robo,4,0.016484

In [37]:
semeion = pd.read_csv("results/semeion_results.csv", index_col="Unnamed: 0")
semeion['dataset'] = 'semeion'
semeion['dim_reduction'] = 40 - semeion['encoding_dim']
semeion['accuracy_reduction'] = semeion['neural_net_acc'] - semeion['auto_classifier_acc']
semeion.head()

,auto_classifier_acc,encoding_dim,neural_net_acc,dataset,dim_reduction,accuracy_reduction
0,0.918239,40,0.91195,semeion,0,-6.289308e-03
1,0.899371,39,0.91195,semeion,1,1.257861e-02
2,0.937107,38,0.91195,semeion,2,-2.515724e-02
3,0.911950,37,0.91195,semeion,3,0.000000e+00
4,0.911950,36,0.91195,semeion,4,-5.623080e-09

In [38]:
results = pd.concat([ionosphere, robo, semeion], axis=0, ignore_index=True)
results.to_csv("results/combined_results")

In [48]:
results[results['accuracy_reduction'] < 0]
results.iloc[results.groupby('dataset').accuracy_reduction.idxmin()]

,auto_classifier_acc,encoding_dim,neural_net_acc,dataset,dim_reduction,accuracy_reduction
0,0.942857,33,0.857143,ionosphere,0,-0.085714
36,0.959707,21,0.945055,robo,3,-0.014652
59,0.937107,38,0.911950,semeion,2,-0.025157